import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Home from '@/components/home/Home'
import About from '@/components/home/About'
import Team from '@/components/home/Team'
import Projects from '@/components/home/Projects'
import ClientSays from '@/components/home/ClientSays'
import Testimonials from '@/components/home/Testimonials'
import Services from '@/components/home/services'
import Pricing from '@/components/home/Pricing'
import NewsSection from '@/components/home/News'
import HaveAproject from '@/components/home/HaveAproject'
import HomeFooter from '@/components/home/HomeFooter'
import Dropdown from './Dropdown'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.13.1/css/all.css"
          integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q"
          crossorigin="anonymous"
        />
      </Head>
      <Dropdown />
      <Home />
      <About />
      <Team />
      <Projects />
      <ClientSays />
      <Testimonials />
      <Services />
      <Pricing />
      <NewsSection />
      <HaveAproject />
      <HomeFooter />
    </>
  );
}
